[package]
name = "genpasswd"
version = "0.4.0"
authors = ["Jesse Stricker"]
description = "An easy-peasy password generator for the command line."
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }

log = "0.4"
env_logger = "0.9"

rand = "0.8"
itertools = "0.10"
